@startuml class

/' ******* ********** **********
********** GLOBAL
********** ********** ********'/
class Launcher extends javafx.application.Application {
    + void Launcher(String[] args)
    + void start(Stage primaryStage)
}


/' ******* ********** **********
********** VIEW
********** ********** ********'/
package "resources.tn.flashcards" #ffecb8 {
    package fxml {
        object vue.fxml
    }

    package css {
        object style.css
    }
}

package "VisualFactory" #ffecb8 {

    class QRViewFactory
    note right: Pattern Factory
    class QRViewFactory {
        +Pane createQRView(Card card)
    }

    abstract QRView extends javafx.scene.layout.Pane {}

    class QRTextView extends QRView {
        # Label txt

        + QRTextView(String txt)
    }

    class QRImageView extends QRView {
        # ImageView img

        + QRImageView(String url)
    }

    class MyBarChart extends javafx.scene.chart.BarChart {
        MyBarChart(int[] donnees)
    }

    class MyPieChart extends javafx.scene.chart.PieChart {
        MyPieChart(int[] donnees)
    }
}


/' ******* ********** **********
********** CONTROLLER
********** ********** ********'/
package "controller" #90d2d8 {

    interface Observateur {
        + void reagir()
    }

    class Controller implements javafx.fxml.Initializable, Observateur {
        +void initialize(URL location, ResourceBundle resources)
    }

}

/' ******* ********** **********
********** MODEL
********** ********** ********'/
package "model" #f6a6b2 {

    class SujetObserve {
        + void ajouterObservateur(Observateur observateur)
        + void notifierObservateur()
    }

    class Data extends SujetObserve {
        - Data instance
        - Data()
        + static Data getInstance()
        + Settings getSettings()
        + ObservableList<Pile> getPiles()
        + Pile getAPile(String id)
        - void addPile(Pile p)
        + void createPile(String name, String creator)
        + void createCard(String pileId, QRType qType, String question, QRType rType, String reponse)
    }
    class Data
    note right: Pattern Singleton

    package pile {

        class Pile {
            # String name
            # String desc
            # String uniqueId
            # String creator

            '+ void nextCard()'

            + void addCard()
        }

        class Card {
            # Int id
        }

        class QuestionRéponse {
            # String content
        }

        enum QRType {}
    }

    package stats {
        class StatsPile {
            # String pileId
            # Int noJeuxPile
            # Int noJeuxCarte
            # Date lastOpened
        }

        class LastStats {
            # Date playDate
            # Int difficulty
        }

        class FullStats extends LastStats {
            # Int cardId
        }

        class DateFormat {
            + static DateTimeFormatter getDateTimeFormatter()
        }


    }

    package settings {

        class Settings {}

        interface StrategyChoix
        note right: Pattern Strategy
        interface StrategyChoix {
            + Card execute()
        }

        class StrategyChoixProba implements StrategyChoix{
            + Card execute()
        }

        class StrategyChoixTemps implements StrategyChoix{
            + Card execute()
        }

        class StrategyChoixTProbaEgales implements StrategyChoix{
            + Card execute()
        }

        enum AlgoAffichage {
            TEMPS
            CLIC
        }

        enum Theme {
            CLAIR
            FONCE
            CONTRASTE
        }
    }

}

/' ******* ********** **********
********** RELATIONS
********** ********** ********'/

' GLOBAL
Launcher -->"1" vue.fxml
Launcher -->"1" style.css

' VC
vue.fxml -->"1" Controller

' CM
SujetObserve *-->"*" Observateur


' CONTROLLER
Controller --> QRViewFactory
Controller --> MyBarChart
Controller --> MyPieChart

' MODEL
Pile *--"..*" Card
Card *--"2" QuestionRéponse
QuestionRéponse -->"1" QRType

Data *-->"..*" Pile
Data *-->"1" Settings
Data *-->"..* [HashMap]" StatsPile

Settings -->"1" StrategyChoix
Settings -->"1" AlgoAffichage
Settings -->"1" Theme

StatsPile -->"..* [HashMap]" LastStats
StatsPile -->"..*" FullStats

' HIDDEN
FullStats -d[hidden]-> DateFormat
javafx.fxml.Initializable -d[hidden]-> Observateur
MyBarChart -l[hidden]-> QRView
MyPieChart -l[hidden]-> MyBarChart
javafx.scene.layout -l[hidden]-> javafx.scene.chart.BarChart

@enduml